

package gui;

import aplicacion.Empleado;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author davi8d
 */
public class VAutentificacion extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    
    /** Creates new form VAutentificacion */
    public VAutentificacion(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        centrarVentana(); 
        autenErrorU.setVisible(false);
        autenErrorA.setVisible(false);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
    }

    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        this.setLocation(x, y);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTabuladoAuten = new javax.swing.JTabbedPane();
        panelUsuario = new javax.swing.JPanel();
        autenNomU = new javax.swing.JTextField();
        labelAutenNomU = new javax.swing.JLabel();
        labelAutenConU = new javax.swing.JLabel();
        autenErrorU = new javax.swing.JLabel();
        btnAceptarU = new javax.swing.JButton();
        btnCancelarU = new javax.swing.JButton();
        autenConU = new javax.swing.JPasswordField();
        panelAdministrador = new javax.swing.JPanel();
        labelAutenNomA = new javax.swing.JLabel();
        autenNomA = new javax.swing.JTextField();
        labelAutenConA = new javax.swing.JLabel();
        autenErrorA = new javax.swing.JLabel();
        btnAceptarA = new javax.swing.JButton();
        btnCancelarA = new javax.swing.JButton();
        autenConA = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autentificación de usuarios");
        setModal(true);
        setName("VAutentificacion"); // NOI18N
        setResizable(false);

        autenNomU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reintentoNomU(evt);
            }
        });

        labelAutenNomU.setText("Nombre:");

        labelAutenConU.setText("Contraseña:");

        autenErrorU.setForeground(new java.awt.Color(255, 0, 0));
        autenErrorU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autenErrorU.setText("Autenticación fallida");

        btnAceptarU.setText("Aceptar");
        btnAceptarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarUActionPerformed(evt);
            }
        });

        btnCancelarU.setText("Cancelar");
        btnCancelarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarUActionPerformed(evt);
            }
        });

        autenConU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reintentoConU(evt);
            }
        });

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(btnAceptarU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(btnCancelarU))
                    .addComponent(autenErrorU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUsuarioLayout.createSequentialGroup()
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAutenConU)
                            .addComponent(labelAutenNomU))
                        .addGap(18, 18, 18)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(autenNomU, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(autenConU))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAutenNomU)
                    .addComponent(autenNomU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAutenConU)
                    .addComponent(autenConU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(autenErrorU)
                .addGap(18, 18, 18)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarU)
                    .addComponent(btnAceptarU))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        autenNomU.getAccessibleContext().setAccessibleName("autenNomU");
        labelAutenNomU.getAccessibleContext().setAccessibleName("labelAutenNomU");
        labelAutenConU.getAccessibleContext().setAccessibleName("labelAutenConU");

        PanelTabuladoAuten.addTab("Usuario", panelUsuario);

        labelAutenNomA.setText("Nombre:");

        labelAutenConA.setText("Contraseña:");

        autenErrorA.setForeground(new java.awt.Color(255, 0, 0));
        autenErrorA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autenErrorA.setText("Autenticación fallida");

        btnAceptarA.setText("Aceptar");
        btnAceptarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarAActionPerformed(evt);
            }
        });

        btnCancelarA.setText("Cancelar");
        btnCancelarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdministradorLayout = new javax.swing.GroupLayout(panelAdministrador);
        panelAdministrador.setLayout(panelAdministradorLayout);
        panelAdministradorLayout.setHorizontalGroup(
            panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministradorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdministradorLayout.createSequentialGroup()
                        .addComponent(btnAceptarA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(btnCancelarA))
                    .addComponent(autenErrorA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAdministradorLayout.createSequentialGroup()
                        .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAutenConA)
                            .addComponent(labelAutenNomA))
                        .addGap(18, 18, 18)
                        .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autenNomA)
                            .addComponent(autenConA))))
                .addGap(19, 19, 19))
        );
        panelAdministradorLayout.setVerticalGroup(
            panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autenNomA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAutenNomA))
                .addGap(18, 18, 18)
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAutenConA)
                    .addComponent(autenConA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(autenErrorA)
                .addGap(18, 18, 18)
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarA)
                    .addComponent(btnCancelarA))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        labelAutenNomA.getAccessibleContext().setAccessibleName("labelAutenNomA");
        autenNomA.getAccessibleContext().setAccessibleName("autenNomA");
        labelAutenConA.getAccessibleContext().setAccessibleName("labelAutenConA");

        PanelTabuladoAuten.addTab("Administrador", panelAdministrador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTabuladoAuten, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTabuladoAuten, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarUActionPerformed

    }//GEN-LAST:event_btnAceptarUActionPerformed

    private void btnCancelarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarUActionPerformed

    }//GEN-LAST:event_btnCancelarUActionPerformed

    private void btnAceptarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarAActionPerformed
        Empleado empleado;
        
        empleado = fa.validarAdministrador(autenNomA.getText(), autenConA.getText());
        
        if (empleado==null){
            autenErrorA.setVisible(true);
        }else{
            fa.iniciaFachadaEmpleado();
            this.dispose();
        }
    }//GEN-LAST:event_btnAceptarAActionPerformed

    private void btnCancelarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarAActionPerformed

    private void reintentoNomU(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reintentoNomU
        autenErrorU.setVisible(false);
    }//GEN-LAST:event_reintentoNomU

    private void reintentoConU(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reintentoConU
        autenErrorU.setVisible(false);
    }//GEN-LAST:event_reintentoConU

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelTabuladoAuten;
    private javax.swing.JPasswordField autenConA;
    private javax.swing.JPasswordField autenConU;
    private javax.swing.JLabel autenErrorA;
    private javax.swing.JLabel autenErrorU;
    private javax.swing.JTextField autenNomA;
    private javax.swing.JTextField autenNomU;
    private javax.swing.JButton btnAceptarA;
    private javax.swing.JButton btnAceptarU;
    private javax.swing.JButton btnCancelarA;
    private javax.swing.JButton btnCancelarU;
    private javax.swing.JLabel labelAutenConA;
    private javax.swing.JLabel labelAutenConU;
    private javax.swing.JLabel labelAutenNomA;
    private javax.swing.JLabel labelAutenNomU;
    private javax.swing.JPanel panelAdministrador;
    private javax.swing.JPanel panelUsuario;
    // End of variables declaration//GEN-END:variables

}
