
package gui;

import aplicacion.Zonas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;

/**
 *
 * @author david
 */

public class VCantidad extends javax.swing.JDialog {

    private List<Float> acambiar;
    private int fila;
    private ModeloTablaProductosReceta m;
    
    /**
     * Creates new form VCantidad
     */
    public VCantidad(java.awt.Frame parent, boolean modal,ModeloTablaProductosReceta m, List<Float> acambiar,int fila) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        centrarVentana(); 
        this.acambiar=acambiar;
        this.fila=fila;
        this.m=m;
    }
    
    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        this.setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CantidadField = new javax.swing.JTextField();
        AceptarCantidad = new javax.swing.JButton();
        CancelarCantidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cantidad");

        jLabel1.setText("Cantidad:");

        AceptarCantidad.setText("Aceptar");
        AceptarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCantidadActionPerformed(evt);
            }
        });

        CancelarCantidad.setText("Cancelar");
        CancelarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(CantidadField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AceptarCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelarCantidad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CantidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarCantidad)
                    .addComponent(CancelarCantidad))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCantidadActionPerformed
        acambiar.set(fila,Float.valueOf(CantidadField.getText()));
        m.fireTableDataChanged();
        this.dispose();
    }//GEN-LAST:event_AceptarCantidadActionPerformed

    private void CancelarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCantidadActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarCantidadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarCantidad;
    private javax.swing.JButton CancelarCantidad;
    private javax.swing.JTextField CantidadField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
