
package gui;

import aplicacion.Decoracion;
import aplicacion.Empleado;
import aplicacion.FachadaAplicacion;
import aplicacion.Producto;
import java.util.List;
import java.util.ArrayList;
import aplicacion.Receta;
import aplicacion.Servicios;
import javax.swing.JFrame;


/**
 *
 * @author alumnogreibd
 */
public class VEmRePrDeSe extends javax.swing.JDialog {

    /**
     * Creates new form VEmRePrDeSe
     */
    
    private FachadaAplicacion fa;
    private FachadaGui fgui;
    
    private ModeloTablaRecetas modeloRecetas;
    private ModeloTablaEmpleados modeloEmpleados;
    private ModeloTablaProductos modeloProductos;
    private ModeloTablaDecoraciones modeloDecoraciones;
    private ModeloTablaServicios modeloServicios;
    
    public VEmRePrDeSe(java.awt.Frame parent, boolean modal,FachadaAplicacion fa,FachadaGui fgui) {
        super(parent, modal);
        initComponents();
        this.fa=fa;
        this.fgui=fgui;
        ModeloTablaRecetas modeloRecetas=new ModeloTablaRecetas();
        jTableRecetas.setModel(modeloRecetas);
        this.modeloRecetas=modeloRecetas;
        ModeloTablaEmpleados modeloEmpleados=new ModeloTablaEmpleados();
        jTableEmpleados.setModel(modeloEmpleados);
        this.modeloEmpleados=modeloEmpleados;
        ModeloTablaProductos modeloProductos=new ModeloTablaProductos();
        jTableProductos.setModel(modeloProductos);
        this.modeloProductos=modeloProductos;
        ModeloTablaDecoraciones modeloDecoraciones=new ModeloTablaDecoraciones();
        jTableDecoraciones.setModel(modeloDecoraciones);
        this.modeloDecoraciones=modeloDecoraciones;
        ModeloTablaServicios modeloServicios=new ModeloTablaServicios();
        jTableServicios.setModel(modeloServicios);
        this.modeloServicios=modeloServicios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneEmRePrDeSe = new javax.swing.JTabbedPane();
        jPanelEmpleados = new javax.swing.JPanel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelRol = new javax.swing.JLabel();
        jLabelNombreEmpleados = new javax.swing.JLabel();
        jLabelOrdenarPor = new javax.swing.JLabel();
        jTextFielddni = new javax.swing.JTextField();
        jTextFieldRol = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBoxOrdenarPorEmpleados = new javax.swing.JComboBox<>();
        jScrollPaneEmpleados = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButtonAnhadirEmpleado = new javax.swing.JButton();
        jButtonModificarEmpleado = new javax.swing.JButton();
        jButtonSalirEmpleados = new javax.swing.JButton();
        jButtonBorrarEmpleado = new javax.swing.JButton();
        jButtonBuscarEmpleados = new javax.swing.JButton();
        jPanelRecetas = new javax.swing.JPanel();
        jLabelNombreRecetas = new javax.swing.JLabel();
        jLabelOrdenarPorRecetas = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldNombreRecetas = new javax.swing.JTextField();
        jTextFieldPrecioRecetas = new javax.swing.JTextField();
        jButtonBuscarRecetas = new javax.swing.JButton();
        jComboBoxOrdenarPorRecetas = new javax.swing.JComboBox<>();
        jScrollPaneRecetas = new javax.swing.JScrollPane();
        jTableRecetas = new javax.swing.JTable();
        jButtonAnhadirReceta = new javax.swing.JButton();
        jButtonSalirReceta = new javax.swing.JButton();
        jButtonBorrarReceta = new javax.swing.JButton();
        jButtonModificarReceta = new javax.swing.JButton();
        jPanelProductos = new javax.swing.JPanel();
        jButtonModificarProducto = new javax.swing.JButton();
        jLabelNombreProductos = new javax.swing.JLabel();
        jLabelOrdenarPorProductos = new javax.swing.JLabel();
        jLabelPrecioProductos = new javax.swing.JLabel();
        jTextFieldNombreProductos = new javax.swing.JTextField();
        jComboBoxOrdenarPorProductos = new javax.swing.JComboBox<>();
        jTextFieldPrecioProductos = new javax.swing.JTextField();
        jButtonBuscarProductos = new javax.swing.JButton();
        jButtonAnhadirProducto = new javax.swing.JButton();
        jButtonBorrarProducto = new javax.swing.JButton();
        jButtonSalirProducto = new javax.swing.JButton();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanelDecoraciones = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelOrdenarPorDecoraciones = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxOrdenarPorDecoraciones = new javax.swing.JComboBox<>();
        jTextFieldTipo = new javax.swing.JTextField();
        jScrollPaneDecoraciones = new javax.swing.JScrollPane();
        jTableDecoraciones = new javax.swing.JTable();
        jButtonBuscarDecoraciones = new javax.swing.JButton();
        jButtonAnhadirDecoracion = new javax.swing.JButton();
        jButtonModificarDecoracion = new javax.swing.JButton();
        jButtonBorrarDecoracion = new javax.swing.JButton();
        jButtonSalirDecoracion = new javax.swing.JButton();
        jPanelServicios = new javax.swing.JPanel();
        jLabelNombreServicio = new javax.swing.JLabel();
        jTextFieldNombreServicios = new javax.swing.JTextField();
        jLabelOrdenarPorServicios = new javax.swing.JLabel();
        jComboBoxServicios = new javax.swing.JComboBox<>();
        jButtonBuscarServicios = new javax.swing.JButton();
        jScrollPaneServicios = new javax.swing.JScrollPane();
        jTableServicios = new javax.swing.JTable();
        jButtonAnhadirServicio = new javax.swing.JButton();
        jButtonModificarServicio = new javax.swing.JButton();
        jButtonBorrarServicio = new javax.swing.JButton();
        jButtonSalirServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión general");

        jLabelDNI.setText("DNI:");

        jLabelRol.setText("Rol:");

        jLabelNombreEmpleados.setText("Nombre:");

        jLabelOrdenarPor.setText("Ordenar por:");

        jComboBoxOrdenarPorEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orden alfabético (ascendente)", "Orden alfabético (descendente)" }));

        jTableEmpleados.setModel(new ModeloTablaEmpleados());
        jScrollPaneEmpleados.setViewportView(jTableEmpleados);

        jButtonAnhadirEmpleado.setText("Añadir");
        jButtonAnhadirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhadirEmpleadoActionPerformed(evt);
            }
        });

        jButtonModificarEmpleado.setText("Modificar");
        jButtonModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEmpleadoActionPerformed(evt);
            }
        });

        jButtonSalirEmpleados.setText("Salir");
        jButtonSalirEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirEmpleadosActionPerformed(evt);
            }
        });

        jButtonBorrarEmpleado.setText("Borrar");
        jButtonBorrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarEmpleadoActionPerformed(evt);
            }
        });

        jButtonBuscarEmpleados.setText("Buscar");
        jButtonBuscarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmpleadosLayout = new javax.swing.GroupLayout(jPanelEmpleados);
        jPanelEmpleados.setLayout(jPanelEmpleadosLayout);
        jPanelEmpleadosLayout.setHorizontalGroup(
            jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneEmpleados)
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabelDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFielddni))
                            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabelRol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldRol)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabelNombreEmpleados)
                                .addGap(37, 37, 37)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabelOrdenarPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxOrdenarPorEmpleados, 0, 1, Short.MAX_VALUE)))
                        .addGap(26, 26, 26)
                        .addComponent(jButtonBuscarEmpleados))
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirEmpleado)
                        .addGap(161, 161, 161)
                        .addComponent(jButtonModificarEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(jButtonBorrarEmpleado)
                        .addGap(145, 145, 145)
                        .addComponent(jButtonSalirEmpleados)))
                .addContainerGap())
        );
        jPanelEmpleadosLayout.setVerticalGroup(
            jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDNI)
                            .addComponent(jLabelNombreEmpleados)
                            .addComponent(jTextFielddni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRol)
                            .addComponent(jLabelOrdenarPor)
                            .addComponent(jTextFieldRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxOrdenarPorEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButtonBuscarEmpleados)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnhadirEmpleado)
                    .addComponent(jButtonModificarEmpleado)
                    .addComponent(jButtonSalirEmpleados)
                    .addComponent(jButtonBorrarEmpleado))
                .addContainerGap())
        );

        jTabbedPaneEmRePrDeSe.addTab("Empleados", jPanelEmpleados);

        jLabelNombreRecetas.setText("Nombre:");

        jLabelOrdenarPorRecetas.setText("Ordenar por:");

        jLabelPrecio.setText("Precio:");

        jButtonBuscarRecetas.setText("Buscar");
        jButtonBuscarRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarRecetasActionPerformed(evt);
            }
        });

        jComboBoxOrdenarPorRecetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orden alfabético (ascendente)", "Orden alfabético (descendente)", "Precio (ascendente)", "Precio (descendente)" }));

        jTableRecetas.setModel(new ModeloTablaRecetas());
        jScrollPaneRecetas.setViewportView(jTableRecetas);

        jButtonAnhadirReceta.setText("Añadir");
        jButtonAnhadirReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhadirRecetaActionPerformed(evt);
            }
        });

        jButtonSalirReceta.setText("Salir");
        jButtonSalirReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirRecetaActionPerformed(evt);
            }
        });

        jButtonBorrarReceta.setText("Borrar");
        jButtonBorrarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarRecetaActionPerformed(evt);
            }
        });

        jButtonModificarReceta.setText("Modificar");
        jButtonModificarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarRecetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRecetasLayout = new javax.swing.GroupLayout(jPanelRecetas);
        jPanelRecetas.setLayout(jPanelRecetasLayout);
        jPanelRecetasLayout.setHorizontalGroup(
            jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneRecetas)
                    .addGroup(jPanelRecetasLayout.createSequentialGroup()
                        .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrdenarPorRecetas)
                            .addComponent(jLabelNombreRecetas))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombreRecetas)
                            .addComponent(jComboBoxOrdenarPorRecetas, 0, 310, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecioRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarRecetas)))
                    .addGroup(jPanelRecetasLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirReceta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificarReceta)
                        .addGap(108, 108, 108)
                        .addComponent(jButtonBorrarReceta)
                        .addGap(179, 179, 179)
                        .addComponent(jButtonSalirReceta)))
                .addContainerGap())
        );
        jPanelRecetasLayout.setVerticalGroup(
            jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecetasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreRecetas)
                    .addComponent(jLabelPrecio)
                    .addComponent(jTextFieldNombreRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecioRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrdenarPorRecetas)
                    .addComponent(jButtonBuscarRecetas)
                    .addComponent(jComboBoxOrdenarPorRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnhadirReceta)
                    .addComponent(jButtonSalirReceta)
                    .addComponent(jButtonBorrarReceta)
                    .addComponent(jButtonModificarReceta))
                .addContainerGap())
        );

        jTabbedPaneEmRePrDeSe.addTab("Recetas", jPanelRecetas);

        jButtonModificarProducto.setText("Modificar");
        jButtonModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarProductoActionPerformed(evt);
            }
        });

        jLabelNombreProductos.setText("Nombre:");

        jLabelOrdenarPorProductos.setText("Ordenar por:");

        jLabelPrecioProductos.setText("Precio:");

        jComboBoxOrdenarPorProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orden alfabético (ascendente)", "Orden alfabético (descendente)", "Precio (ascendente)", "Precio (descendente)" }));

        jButtonBuscarProductos.setText("Buscar");
        jButtonBuscarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductosActionPerformed(evt);
            }
        });

        jButtonAnhadirProducto.setText("Añadir");
        jButtonAnhadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhadirProductoActionPerformed(evt);
            }
        });

        jButtonBorrarProducto.setText("Borrar");
        jButtonBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarProductoActionPerformed(evt);
            }
        });

        jButtonSalirProducto.setText("Salir");
        jButtonSalirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirProductoActionPerformed(evt);
            }
        });

        jTableProductos.setModel(new ModeloTablaProductos());
        jScrollPaneProductos.setViewportView(jTableProductos);

        javax.swing.GroupLayout jPanelProductosLayout = new javax.swing.GroupLayout(jPanelProductos);
        jPanelProductos.setLayout(jPanelProductosLayout);
        jPanelProductosLayout.setHorizontalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductosLayout.createSequentialGroup()
                        .addComponent(jScrollPaneProductos)
                        .addContainerGap())
                    .addGroup(jPanelProductosLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirProducto)
                        .addGap(189, 189, 189)
                        .addComponent(jButtonModificarProducto)
                        .addGap(123, 123, 123)
                        .addComponent(jButtonBorrarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(jButtonSalirProducto)
                        .addContainerGap())
                    .addGroup(jPanelProductosLayout.createSequentialGroup()
                        .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProductosLayout.createSequentialGroup()
                                .addComponent(jLabelNombreProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPrecioProductos)
                                .addGap(10, 10, 10))
                            .addGroup(jPanelProductosLayout.createSequentialGroup()
                                .addComponent(jLabelOrdenarPorProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNombreProductos)
                                    .addComponent(jComboBoxOrdenarPorProductos, 0, 338, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecioProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarProductos))
                        .addGap(14, 14, 14))))
        );
        jPanelProductosLayout.setVerticalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreProductos)
                    .addComponent(jLabelPrecioProductos)
                    .addComponent(jTextFieldNombreProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecioProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrdenarPorProductos)
                    .addComponent(jComboBoxOrdenarPorProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarProductos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificarProducto)
                    .addComponent(jButtonAnhadirProducto)
                    .addComponent(jButtonBorrarProducto)
                    .addComponent(jButtonSalirProducto))
                .addContainerGap())
        );

        jTabbedPaneEmRePrDeSe.addTab("Productos", jPanelProductos);

        jLabelId.setText("Id:");

        jLabelModelo.setText("Modelo:");

        jLabelTipo.setText("Tipo:");

        jLabelOrdenarPorDecoraciones.setText("Ordenar por:");

        jComboBoxOrdenarPorDecoraciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orden alfabético del modelo (ascendente)", "Orden alfabético del modelo (descendente)", "Id (ascendente)", "Id (descendente)" }));

        jTableDecoraciones.setModel(new ModeloTablaDecoraciones());
        jScrollPaneDecoraciones.setViewportView(jTableDecoraciones);

        jButtonBuscarDecoraciones.setText("Buscar");
        jButtonBuscarDecoraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDecoracionesActionPerformed(evt);
            }
        });

        jButtonAnhadirDecoracion.setText("Añadir");
        jButtonAnhadirDecoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhadirDecoracionActionPerformed(evt);
            }
        });

        jButtonModificarDecoracion.setText("Modificar");
        jButtonModificarDecoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarDecoracionActionPerformed(evt);
            }
        });

        jButtonBorrarDecoracion.setText("Borrar");
        jButtonBorrarDecoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarDecoracionActionPerformed(evt);
            }
        });

        jButtonSalirDecoracion.setText("Salir");
        jButtonSalirDecoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirDecoracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDecoracionesLayout = new javax.swing.GroupLayout(jPanelDecoraciones);
        jPanelDecoraciones.setLayout(jPanelDecoracionesLayout);
        jPanelDecoracionesLayout.setHorizontalGroup(
            jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirDecoracion)
                        .addGap(155, 155, 155)
                        .addComponent(jButtonModificarDecoracion)
                        .addGap(110, 110, 110)
                        .addComponent(jButtonBorrarDecoracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(jButtonSalirDecoracion))
                    .addComponent(jScrollPaneDecoraciones)
                    .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldId)
                            .addComponent(jTextFieldModelo))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrdenarPorDecoraciones)
                            .addComponent(jLabelTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTipo)
                            .addComponent(jComboBoxOrdenarPorDecoraciones, 0, 193, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarDecoraciones)))
                .addContainerGap())
        );
        jPanelDecoracionesLayout.setVerticalGroup(
            jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jLabelTipo)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelOrdenarPorDecoraciones)
                            .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxOrdenarPorDecoraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDecoracionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBuscarDecoraciones)
                        .addGap(31, 31, 31)))
                .addComponent(jScrollPaneDecoraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnhadirDecoracion)
                    .addComponent(jButtonModificarDecoracion)
                    .addComponent(jButtonBorrarDecoracion)
                    .addComponent(jButtonSalirDecoracion))
                .addContainerGap())
        );

        jTabbedPaneEmRePrDeSe.addTab("Decoraciones", jPanelDecoraciones);

        jLabelNombreServicio.setText("Nombre:");

        jLabelOrdenarPorServicios.setText("Ordenar por:");

        jComboBoxServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orden alfabético (ascendente)", "Orden alfabético (descendente)" }));
        jComboBoxServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServiciosActionPerformed(evt);
            }
        });

        jButtonBuscarServicios.setText("Buscar");
        jButtonBuscarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarServiciosActionPerformed(evt);
            }
        });

        jTableServicios.setModel(new ModeloTablaServicios());
        jScrollPaneServicios.setViewportView(jTableServicios);

        jButtonAnhadirServicio.setText("Añadir");
        jButtonAnhadirServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhadirServicioActionPerformed(evt);
            }
        });

        jButtonModificarServicio.setText("Modificar");
        jButtonModificarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarServicioActionPerformed(evt);
            }
        });

        jButtonBorrarServicio.setText("Borrar");
        jButtonBorrarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarServicioActionPerformed(evt);
            }
        });

        jButtonSalirServicio.setText("Salir");
        jButtonSalirServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelServiciosLayout = new javax.swing.GroupLayout(jPanelServicios);
        jPanelServicios.setLayout(jPanelServiciosLayout);
        jPanelServiciosLayout.setHorizontalGroup(
            jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelServiciosLayout.createSequentialGroup()
                        .addComponent(jLabelNombreServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombreServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelOrdenarPorServicios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarServicios)
                        .addGap(31, 31, 31))
                    .addGroup(jPanelServiciosLayout.createSequentialGroup()
                        .addComponent(jScrollPaneServicios)
                        .addContainerGap())
                    .addGroup(jPanelServiciosLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirServicio)
                        .addGap(153, 153, 153)
                        .addComponent(jButtonModificarServicio)
                        .addGap(153, 153, 153)
                        .addComponent(jButtonBorrarServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalirServicio)
                        .addContainerGap())))
        );
        jPanelServiciosLayout.setVerticalGroup(
            jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServiciosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreServicio)
                    .addComponent(jTextFieldNombreServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrdenarPorServicios)
                    .addComponent(jComboBoxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarServicios))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnhadirServicio)
                    .addComponent(jButtonModificarServicio)
                    .addComponent(jButtonBorrarServicio)
                    .addComponent(jButtonSalirServicio))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTabbedPaneEmRePrDeSe.addTab("Servicios", jPanelServicios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneEmRePrDeSe, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneEmRePrDeSe)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarRecetasActionPerformed
        // TODO add your handling code here:
        try{
            List<Receta> recetas=new ArrayList<Receta>();
            if(jTextFieldPrecioRecetas.getText()!=""){
                recetas=fa.buscarRecetas(jTextFieldNombreRecetas.getText(),Float.valueOf(jTextFieldPrecioRecetas.getText()),(String)jComboBoxOrdenarPorRecetas.getSelectedItem());
            }
            else{
                recetas=fa.buscarRecetas(jTextFieldNombreRecetas.getText(),null,(String)jComboBoxOrdenarPorRecetas.getSelectedItem());
            }
            modeloRecetas.setFilas(recetas);
        }
        catch(Exception e){
            fa.muestraExcepcion(e.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarRecetasActionPerformed

    private void jButtonBorrarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarRecetaActionPerformed
        // TODO add your handling code here:
        fa.borrarReceta(modeloRecetas.obteneReceta(jTableRecetas.getSelectedRow()));
    }//GEN-LAST:event_jButtonBorrarRecetaActionPerformed

    private void jButtonSalirRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirRecetaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirRecetaActionPerformed

    private void jButtonModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEmpleadoActionPerformed
        fgui.visualizarModificarEmpleado((JFrame)this.getParent(), modeloEmpleados.obtenerEmpleado(jTableEmpleados.getSelectedRow()));
    }//GEN-LAST:event_jButtonModificarEmpleadoActionPerformed

    private void jButtonModificarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarRecetaActionPerformed
        // TODO add your handling code here:
        fgui.visualizarModificarReceta((JFrame)this.getParent(), modeloRecetas.obteneReceta(jTableRecetas.getSelectedRow()));
    }//GEN-LAST:event_jButtonModificarRecetaActionPerformed

    private void jButtonAnhadirRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhadirRecetaActionPerformed
        // TODO add your handling code here:
        fgui.visualizarAnhadirReceta((JFrame)this.getParent());
    }//GEN-LAST:event_jButtonAnhadirRecetaActionPerformed

    private void jButtonBuscarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEmpleadosActionPerformed
        // TODO add your handling code here:
        try{
            List<Empleado> empleados=new ArrayList<Empleado>();
            empleados=fa.buscarEmpleados(jTextFielddni.getText(),jTextFieldNombre.getText(),jTextFieldRol.getText(),(String)jComboBoxOrdenarPorEmpleados.getSelectedItem());
            modeloEmpleados.setFilas(empleados);
        }
        catch(Exception e){
            fa.muestraExcepcion(e.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarEmpleadosActionPerformed

    private void jButtonSalirEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirEmpleadosActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirEmpleadosActionPerformed

    private void jButtonSalirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirProductoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirProductoActionPerformed

    private void jButtonSalirDecoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirDecoracionActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirDecoracionActionPerformed

    private void jButtonSalirServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirServicioActionPerformed
        VPrincipalE vc;
        vc = new VPrincipalE(fa);
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSalirServicioActionPerformed

    private void jButtonBuscarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductosActionPerformed
        // TODO add your handling code here:
        try{
            List<Producto> productos=new ArrayList<Producto>();
            if(jTextFieldPrecioProductos.getText()!=""){
                productos=fa.buscarProductos(jTextFieldNombreProductos.getText(),Float.valueOf(jTextFieldPrecioProductos.getText()),(String)jComboBoxOrdenarPorProductos.getSelectedItem());
            }
            else{
                productos=fa.buscarProductos(jTextFieldNombreProductos.getText(),null,(String)jComboBoxOrdenarPorProductos.getSelectedItem());
            }
            modeloProductos.setFilas(productos);
        }
        catch(Exception e){
            fa.muestraExcepcion(e.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarProductosActionPerformed

    private void jButtonBuscarDecoracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDecoracionesActionPerformed
        // TODO add your handling code here:
        try{
            List<Decoracion> decoraciones=new ArrayList<Decoracion>();
            decoraciones=fa.buscarDecoraciones(jTextFieldId.getText(),jTextFieldTipo.getText(),jTextFieldModelo.getText(),(String)jComboBoxOrdenarPorDecoraciones.getSelectedItem());
            modeloDecoraciones.setFilas(decoraciones);
        }
        catch(Exception e){
            fa.muestraExcepcion(e.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarDecoracionesActionPerformed

    private void jButtonBuscarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarServiciosActionPerformed
        // TODO add your handling code here:
        try{
            List<Servicios> servicios=new ArrayList<>();
            servicios=fa.buscarServicios(jTextFieldNombreServicios.getText(),(String)jComboBoxServicios.getSelectedItem());
            modeloServicios.setFilas(servicios);
        }
        catch(Exception e){
            fa.muestraExcepcion(e.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarServiciosActionPerformed

    private void jButtonBorrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarEmpleadoActionPerformed
        // TODO add your handling code here:
        fa.borrarEmpleado(modeloEmpleados.obtenerEmpleado(jTableEmpleados.getSelectedRow()));
    }//GEN-LAST:event_jButtonBorrarEmpleadoActionPerformed

    private void jButtonBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarProductoActionPerformed
        // TODO add your handling code here:
        fa.borrarProducto(modeloProductos.obtenerProducto(jTableProductos.getSelectedRow()));
    }//GEN-LAST:event_jButtonBorrarProductoActionPerformed

    private void jButtonBorrarDecoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarDecoracionActionPerformed
        // TODO add your handling code here:
        fa.borrarDecoracion(modeloDecoraciones.obtenerDecoracion(jTableDecoraciones.getSelectedRow()));
    }//GEN-LAST:event_jButtonBorrarDecoracionActionPerformed

    private void jButtonBorrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarServicioActionPerformed
        // TODO add your handling code here:
        fa.borrarServicio(modeloServicios.obtenerServicio(jTableDecoraciones.getSelectedRow()));
    }//GEN-LAST:event_jButtonBorrarServicioActionPerformed

    private void jButtonAnhadirServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhadirServicioActionPerformed
        fgui.visualizarAnhadirServicios((JFrame)this.getParent());
    }//GEN-LAST:event_jButtonAnhadirServicioActionPerformed

    private void jComboBoxServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServiciosActionPerformed

    private void jButtonAnhadirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhadirEmpleadoActionPerformed
        fgui.visualizarAnhadirEmpleado((JFrame)this.getParent());
    }//GEN-LAST:event_jButtonAnhadirEmpleadoActionPerformed

    private void jButtonAnhadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhadirProductoActionPerformed
        fgui.visualizarAnhadirProducto((JFrame)this.getParent());
    }//GEN-LAST:event_jButtonAnhadirProductoActionPerformed

    private void jButtonAnhadirDecoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhadirDecoracionActionPerformed
        fgui.visualizarAnhadirDecoracion((JFrame)this.getParent());
    }//GEN-LAST:event_jButtonAnhadirDecoracionActionPerformed

    private void jButtonModificarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarServicioActionPerformed
        fgui.visualizarModificarServicios((JFrame)this.getParent(), modeloServicios.obtenerServicio(jTableServicios.getSelectedRow()));
    }//GEN-LAST:event_jButtonModificarServicioActionPerformed

    private void jButtonModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarProductoActionPerformed
        fgui.visualizarModificarProducto((JFrame)this.getParent(), modeloProductos.obtenerProducto(jTableProductos.getSelectedRow()));
    }//GEN-LAST:event_jButtonModificarProductoActionPerformed

    private void jButtonModificarDecoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarDecoracionActionPerformed
        fgui.visualizarModificarDecoracion((JFrame)this.getParent(), modeloDecoraciones.obtenerDecoracion(jTableDecoraciones.getSelectedRow()));
    }//GEN-LAST:event_jButtonModificarDecoracionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnhadirDecoracion;
    private javax.swing.JButton jButtonAnhadirEmpleado;
    private javax.swing.JButton jButtonAnhadirProducto;
    private javax.swing.JButton jButtonAnhadirReceta;
    private javax.swing.JButton jButtonAnhadirServicio;
    private javax.swing.JButton jButtonBorrarDecoracion;
    private javax.swing.JButton jButtonBorrarEmpleado;
    private javax.swing.JButton jButtonBorrarProducto;
    private javax.swing.JButton jButtonBorrarReceta;
    private javax.swing.JButton jButtonBorrarServicio;
    private javax.swing.JButton jButtonBuscarDecoraciones;
    private javax.swing.JButton jButtonBuscarEmpleados;
    private javax.swing.JButton jButtonBuscarProductos;
    private javax.swing.JButton jButtonBuscarRecetas;
    private javax.swing.JButton jButtonBuscarServicios;
    private javax.swing.JButton jButtonModificarDecoracion;
    private javax.swing.JButton jButtonModificarEmpleado;
    private javax.swing.JButton jButtonModificarProducto;
    private javax.swing.JButton jButtonModificarReceta;
    private javax.swing.JButton jButtonModificarServicio;
    private javax.swing.JButton jButtonSalirDecoracion;
    private javax.swing.JButton jButtonSalirEmpleados;
    private javax.swing.JButton jButtonSalirProducto;
    private javax.swing.JButton jButtonSalirReceta;
    private javax.swing.JButton jButtonSalirServicio;
    private javax.swing.JComboBox<String> jComboBoxOrdenarPorDecoraciones;
    private javax.swing.JComboBox<String> jComboBoxOrdenarPorEmpleados;
    private javax.swing.JComboBox<String> jComboBoxOrdenarPorProductos;
    private javax.swing.JComboBox<String> jComboBoxOrdenarPorRecetas;
    private javax.swing.JComboBox<String> jComboBoxServicios;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelNombreEmpleados;
    private javax.swing.JLabel jLabelNombreProductos;
    private javax.swing.JLabel jLabelNombreRecetas;
    private javax.swing.JLabel jLabelNombreServicio;
    private javax.swing.JLabel jLabelOrdenarPor;
    private javax.swing.JLabel jLabelOrdenarPorDecoraciones;
    private javax.swing.JLabel jLabelOrdenarPorProductos;
    private javax.swing.JLabel jLabelOrdenarPorRecetas;
    private javax.swing.JLabel jLabelOrdenarPorServicios;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecioProductos;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanelDecoraciones;
    private javax.swing.JPanel jPanelEmpleados;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelRecetas;
    private javax.swing.JPanel jPanelServicios;
    private javax.swing.JScrollPane jScrollPaneDecoraciones;
    private javax.swing.JScrollPane jScrollPaneEmpleados;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JScrollPane jScrollPaneRecetas;
    private javax.swing.JScrollPane jScrollPaneServicios;
    private javax.swing.JTabbedPane jTabbedPaneEmRePrDeSe;
    private javax.swing.JTable jTableDecoraciones;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTable jTableRecetas;
    private javax.swing.JTable jTableServicios;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreProductos;
    private javax.swing.JTextField jTextFieldNombreRecetas;
    private javax.swing.JTextField jTextFieldNombreServicios;
    private javax.swing.JTextField jTextFieldPrecioProductos;
    private javax.swing.JTextField jTextFieldPrecioRecetas;
    private javax.swing.JTextField jTextFieldRol;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFielddni;
    // End of variables declaration//GEN-END:variables
}
