/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author alumnogreibd
 */
public class VGeneral extends javax.swing.JDialog {

    /**
     * Creates new form VEmRePrDeSe
     */
    public VGeneral(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centrarVentana();
        getContentPane().setBackground(Color.WHITE);
    }
    
    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneEmRePrDeSe = new javax.swing.JTabbedPane();
        jPanelEmpleados = new javax.swing.JPanel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelRol = new javax.swing.JLabel();
        jLabelNombreEmpleados = new javax.swing.JLabel();
        jLabelOrdenarPor = new javax.swing.JLabel();
        jTextFielddni = new javax.swing.JTextField();
        jTextFieldRol = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBoxOrdenarPorEmpleados = new javax.swing.JComboBox<>();
        jScrollPaneEmpleados = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButtonAnhadirEmpleado = new javax.swing.JButton();
        jButtonModificarEmpleado = new javax.swing.JButton();
        jButtonSalirEmpleados = new javax.swing.JButton();
        jButtonBorrarEmpleado = new javax.swing.JButton();
        jPanelRecetas = new javax.swing.JPanel();
        jLabelNombreRecetas = new javax.swing.JLabel();
        jLabelOrdenarPorRecetas = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldNombreRecetas = new javax.swing.JTextField();
        jTextFieldPrecioRecetas = new javax.swing.JTextField();
        jButtonBuscarRecetas = new javax.swing.JButton();
        jComboBoxOrdenarPorRecetas = new javax.swing.JComboBox<>();
        jScrollPaneRecetas = new javax.swing.JScrollPane();
        jTableRecetas = new javax.swing.JTable();
        jButtonAnhadirReceta = new javax.swing.JButton();
        jButtonSalirReceta = new javax.swing.JButton();
        jButtonBorrarReceta = new javax.swing.JButton();
        jButtonModificarReceta = new javax.swing.JButton();
        jPanelProductos = new javax.swing.JPanel();
        jButtonModificarProducto = new javax.swing.JButton();
        jLabelNombreProductos = new javax.swing.JLabel();
        jLabelOrdenarPorProductos = new javax.swing.JLabel();
        jLabelPrecioProductos = new javax.swing.JLabel();
        jTextFieldNombreProductos = new javax.swing.JTextField();
        jComboBoxOrdenarPorProductos = new javax.swing.JComboBox<>();
        jTextFieldPrecioProductos = new javax.swing.JTextField();
        jButtonBuscarProductos = new javax.swing.JButton();
        jButtonAnhadirProducto = new javax.swing.JButton();
        jButtonBorrarProducto = new javax.swing.JButton();
        jButtonSalirProducto = new javax.swing.JButton();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanelDecoraciones = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelOrdenarPorDecoraciones = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxOrdenarPorDecoraciones = new javax.swing.JComboBox<>();
        jTextFieldTipo = new javax.swing.JTextField();
        jScrollPaneDecoraciones = new javax.swing.JScrollPane();
        jTableDecoraciones = new javax.swing.JTable();
        jButtonBuscarDecoraciones = new javax.swing.JButton();
        jButtonAnhadirDecoracion = new javax.swing.JButton();
        jButtonModificarDecoracion = new javax.swing.JButton();
        jButtonBorrarDecoracion = new javax.swing.JButton();
        jButtonSalirDecoracion = new javax.swing.JButton();
        jPanelServicios = new javax.swing.JPanel();
        jLabelNombreServicio = new javax.swing.JLabel();
        jTextFieldNombreServicios = new javax.swing.JTextField();
        jLabelOrdenarPorServicios = new javax.swing.JLabel();
        jComboBoxServicios = new javax.swing.JComboBox<>();
        jButtonBuscarServicios = new javax.swing.JButton();
        jScrollPaneServicios = new javax.swing.JScrollPane();
        jTableServicios = new javax.swing.JTable();
        jButtonAnhadirServicio = new javax.swing.JButton();
        jButtonModificarServicio = new javax.swing.JButton();
        jButtonBorrarServicio = new javax.swing.JButton();
        jButtonSalirServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelDNI.setText("DNI:");

        jLabelRol.setText("Rol:");

        jLabelNombreEmpleados.setText("Nombre:");

        jLabelOrdenarPor.setText("Ordenar por:");

        jComboBoxOrdenarPorEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneEmpleados.setViewportView(jTableEmpleados);

        jButtonAnhadirEmpleado.setText("Añadir");

        jButtonModificarEmpleado.setText("Modificar");

        jButtonSalirEmpleados.setText("Salir");

        jButtonBorrarEmpleado.setText("Borrar");

        javax.swing.GroupLayout jPanelEmpleadosLayout = new javax.swing.GroupLayout(jPanelEmpleados);
        jPanelEmpleados.setLayout(jPanelEmpleadosLayout);
        jPanelEmpleadosLayout.setHorizontalGroup(
            jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneEmpleados)
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabelDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFielddni))
                            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabelRol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldRol)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabelNombreEmpleados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                .addComponent(jLabelOrdenarPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxOrdenarPorEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirEmpleado)
                        .addGap(161, 161, 161)
                        .addComponent(jButtonModificarEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(jButtonBorrarEmpleado)
                        .addGap(145, 145, 145)
                        .addComponent(jButtonSalirEmpleados)))
                .addContainerGap())
        );
        jPanelEmpleadosLayout.setVerticalGroup(
            jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI)
                    .addComponent(jLabelNombreEmpleados)
                    .addComponent(jTextFielddni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRol)
                    .addComponent(jLabelOrdenarPor)
                    .addComponent(jTextFieldRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOrdenarPorEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnhadirEmpleado)
                    .addComponent(jButtonModificarEmpleado)
                    .addComponent(jButtonSalirEmpleados)
                    .addComponent(jButtonBorrarEmpleado))
                .addContainerGap())
        );

        jTabbedPaneEmRePrDeSe.addTab("Empleados", jPanelEmpleados);

        jLabelNombreRecetas.setText("Nombre:");

        jLabelOrdenarPorRecetas.setText("Ordenar por:");

        jLabelPrecio.setText("Precio:");

        jButtonBuscarRecetas.setText("Buscar");

        jComboBoxOrdenarPorRecetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneRecetas.setViewportView(jTableRecetas);

        jButtonAnhadirReceta.setText("Añadir");

        jButtonSalirReceta.setText("Salir");

        jButtonBorrarReceta.setText("Borrar");

        jButtonModificarReceta.setText("Modificar");

        javax.swing.GroupLayout jPanelRecetasLayout = new javax.swing.GroupLayout(jPanelRecetas);
        jPanelRecetas.setLayout(jPanelRecetasLayout);
        jPanelRecetasLayout.setHorizontalGroup(
            jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneRecetas)
                    .addGroup(jPanelRecetasLayout.createSequentialGroup()
                        .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrdenarPorRecetas)
                            .addComponent(jLabelNombreRecetas))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombreRecetas)
                            .addComponent(jComboBoxOrdenarPorRecetas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecioRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarRecetas)))
                    .addGroup(jPanelRecetasLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirReceta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificarReceta)
                        .addGap(108, 108, 108)
                        .addComponent(jButtonBorrarReceta)
                        .addGap(179, 179, 179)
                        .addComponent(jButtonSalirReceta)))
                .addContainerGap())
        );
        jPanelRecetasLayout.setVerticalGroup(
            jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecetasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreRecetas)
                    .addComponent(jLabelPrecio)
                    .addComponent(jTextFieldNombreRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecioRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrdenarPorRecetas)
                    .addComponent(jButtonBuscarRecetas)
                    .addComponent(jComboBoxOrdenarPorRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnhadirReceta)
                    .addComponent(jButtonSalirReceta)
                    .addComponent(jButtonBorrarReceta)
                    .addComponent(jButtonModificarReceta))
                .addContainerGap())
        );

        jTabbedPaneEmRePrDeSe.addTab("Recetas", jPanelRecetas);

        jButtonModificarProducto.setText("Modificar");

        jLabelNombreProductos.setText("Nombre:");

        jLabelOrdenarPorProductos.setText("Ordenar por:");

        jLabelPrecioProductos.setText("Precio:");

        jComboBoxOrdenarPorProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonBuscarProductos.setText("Buscar");

        jButtonAnhadirProducto.setText("Añadir");

        jButtonBorrarProducto.setText("Borrar");

        jButtonSalirProducto.setText("Salir");

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneProductos.setViewportView(jTableProductos);

        javax.swing.GroupLayout jPanelProductosLayout = new javax.swing.GroupLayout(jPanelProductos);
        jPanelProductos.setLayout(jPanelProductosLayout);
        jPanelProductosLayout.setHorizontalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductosLayout.createSequentialGroup()
                        .addComponent(jScrollPaneProductos)
                        .addContainerGap())
                    .addGroup(jPanelProductosLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirProducto)
                        .addGap(189, 189, 189)
                        .addComponent(jButtonModificarProducto)
                        .addGap(123, 123, 123)
                        .addComponent(jButtonBorrarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(jButtonSalirProducto)
                        .addContainerGap())
                    .addGroup(jPanelProductosLayout.createSequentialGroup()
                        .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProductosLayout.createSequentialGroup()
                                .addComponent(jLabelNombreProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPrecioProductos)
                                .addGap(10, 10, 10))
                            .addGroup(jPanelProductosLayout.createSequentialGroup()
                                .addComponent(jLabelOrdenarPorProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNombreProductos)
                                    .addComponent(jComboBoxOrdenarPorProductos, 0, 338, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecioProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarProductos))
                        .addGap(14, 14, 14))))
        );
        jPanelProductosLayout.setVerticalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreProductos)
                    .addComponent(jLabelPrecioProductos)
                    .addComponent(jTextFieldNombreProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecioProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrdenarPorProductos)
                    .addComponent(jComboBoxOrdenarPorProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarProductos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificarProducto)
                    .addComponent(jButtonAnhadirProducto)
                    .addComponent(jButtonBorrarProducto)
                    .addComponent(jButtonSalirProducto))
                .addContainerGap())
        );

        jTabbedPaneEmRePrDeSe.addTab("Productos", jPanelProductos);

        jLabelId.setText("Id:");

        jLabelModelo.setText("Modelo:");

        jLabelTipo.setText("Tipo:");

        jLabelOrdenarPorDecoraciones.setText("Ordenar por:");

        jComboBoxOrdenarPorDecoraciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableDecoraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneDecoraciones.setViewportView(jTableDecoraciones);

        jButtonBuscarDecoraciones.setText("Buscar");

        jButtonAnhadirDecoracion.setText("Añadir");

        jButtonModificarDecoracion.setText("Modificar");

        jButtonBorrarDecoracion.setText("Borrar");

        jButtonSalirDecoracion.setText("Salir");

        javax.swing.GroupLayout jPanelDecoracionesLayout = new javax.swing.GroupLayout(jPanelDecoraciones);
        jPanelDecoraciones.setLayout(jPanelDecoracionesLayout);
        jPanelDecoracionesLayout.setHorizontalGroup(
            jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirDecoracion)
                        .addGap(155, 155, 155)
                        .addComponent(jButtonModificarDecoracion)
                        .addGap(110, 110, 110)
                        .addComponent(jButtonBorrarDecoracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(jButtonSalirDecoracion))
                    .addComponent(jScrollPaneDecoraciones)
                    .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldId)
                            .addComponent(jTextFieldModelo))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrdenarPorDecoraciones)
                            .addComponent(jLabelTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTipo)
                            .addComponent(jComboBoxOrdenarPorDecoraciones, 0, 193, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarDecoraciones)))
                .addContainerGap())
        );
        jPanelDecoracionesLayout.setVerticalGroup(
            jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDecoracionesLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jLabelTipo)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelOrdenarPorDecoraciones)
                            .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxOrdenarPorDecoraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDecoracionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBuscarDecoraciones)
                        .addGap(31, 31, 31)))
                .addComponent(jScrollPaneDecoraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelDecoracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnhadirDecoracion)
                    .addComponent(jButtonModificarDecoracion)
                    .addComponent(jButtonBorrarDecoracion)
                    .addComponent(jButtonSalirDecoracion))
                .addContainerGap())
        );

        jTabbedPaneEmRePrDeSe.addTab("Decoraciones", jPanelDecoraciones);

        jLabelNombreServicio.setText("Nombre:");

        jLabelOrdenarPorServicios.setText("Ordenar por:");

        jComboBoxServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonBuscarServicios.setText("Buscar");

        jTableServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneServicios.setViewportView(jTableServicios);

        jButtonAnhadirServicio.setText("Añadir");

        jButtonModificarServicio.setText("Modificar");

        jButtonBorrarServicio.setText("Borrar");

        jButtonSalirServicio.setText("Salir");

        javax.swing.GroupLayout jPanelServiciosLayout = new javax.swing.GroupLayout(jPanelServicios);
        jPanelServicios.setLayout(jPanelServiciosLayout);
        jPanelServiciosLayout.setHorizontalGroup(
            jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelServiciosLayout.createSequentialGroup()
                        .addComponent(jLabelNombreServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombreServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelOrdenarPorServicios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarServicios)
                        .addGap(31, 31, 31))
                    .addGroup(jPanelServiciosLayout.createSequentialGroup()
                        .addComponent(jScrollPaneServicios)
                        .addContainerGap())
                    .addGroup(jPanelServiciosLayout.createSequentialGroup()
                        .addComponent(jButtonAnhadirServicio)
                        .addGap(153, 153, 153)
                        .addComponent(jButtonModificarServicio)
                        .addGap(153, 153, 153)
                        .addComponent(jButtonBorrarServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalirServicio)
                        .addContainerGap())))
        );
        jPanelServiciosLayout.setVerticalGroup(
            jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServiciosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreServicio)
                    .addComponent(jTextFieldNombreServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrdenarPorServicios)
                    .addComponent(jComboBoxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarServicios))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnhadirServicio)
                    .addComponent(jButtonModificarServicio)
                    .addComponent(jButtonBorrarServicio)
                    .addComponent(jButtonSalirServicio))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTabbedPaneEmRePrDeSe.addTab("Servicios", jPanelServicios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneEmRePrDeSe, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneEmRePrDeSe)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnhadirDecoracion;
    private javax.swing.JButton jButtonAnhadirEmpleado;
    private javax.swing.JButton jButtonAnhadirProducto;
    private javax.swing.JButton jButtonAnhadirReceta;
    private javax.swing.JButton jButtonAnhadirServicio;
    private javax.swing.JButton jButtonBorrarDecoracion;
    private javax.swing.JButton jButtonBorrarEmpleado;
    private javax.swing.JButton jButtonBorrarProducto;
    private javax.swing.JButton jButtonBorrarReceta;
    private javax.swing.JButton jButtonBorrarServicio;
    private javax.swing.JButton jButtonBuscarDecoraciones;
    private javax.swing.JButton jButtonBuscarProductos;
    private javax.swing.JButton jButtonBuscarRecetas;
    private javax.swing.JButton jButtonBuscarServicios;
    private javax.swing.JButton jButtonModificarDecoracion;
    private javax.swing.JButton jButtonModificarEmpleado;
    private javax.swing.JButton jButtonModificarProducto;
    private javax.swing.JButton jButtonModificarReceta;
    private javax.swing.JButton jButtonModificarServicio;
    private javax.swing.JButton jButtonSalirDecoracion;
    private javax.swing.JButton jButtonSalirEmpleados;
    private javax.swing.JButton jButtonSalirProducto;
    private javax.swing.JButton jButtonSalirReceta;
    private javax.swing.JButton jButtonSalirServicio;
    private javax.swing.JComboBox<String> jComboBoxOrdenarPorDecoraciones;
    private javax.swing.JComboBox<String> jComboBoxOrdenarPorEmpleados;
    private javax.swing.JComboBox<String> jComboBoxOrdenarPorProductos;
    private javax.swing.JComboBox<String> jComboBoxOrdenarPorRecetas;
    private javax.swing.JComboBox<String> jComboBoxServicios;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelNombreEmpleados;
    private javax.swing.JLabel jLabelNombreProductos;
    private javax.swing.JLabel jLabelNombreRecetas;
    private javax.swing.JLabel jLabelNombreServicio;
    private javax.swing.JLabel jLabelOrdenarPor;
    private javax.swing.JLabel jLabelOrdenarPorDecoraciones;
    private javax.swing.JLabel jLabelOrdenarPorProductos;
    private javax.swing.JLabel jLabelOrdenarPorRecetas;
    private javax.swing.JLabel jLabelOrdenarPorServicios;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecioProductos;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanelDecoraciones;
    private javax.swing.JPanel jPanelEmpleados;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelRecetas;
    private javax.swing.JPanel jPanelServicios;
    private javax.swing.JScrollPane jScrollPaneDecoraciones;
    private javax.swing.JScrollPane jScrollPaneEmpleados;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JScrollPane jScrollPaneRecetas;
    private javax.swing.JScrollPane jScrollPaneServicios;
    private javax.swing.JTabbedPane jTabbedPaneEmRePrDeSe;
    private javax.swing.JTable jTableDecoraciones;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTable jTableRecetas;
    private javax.swing.JTable jTableServicios;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreProductos;
    private javax.swing.JTextField jTextFieldNombreRecetas;
    private javax.swing.JTextField jTextFieldNombreServicios;
    private javax.swing.JTextField jTextFieldPrecioProductos;
    private javax.swing.JTextField jTextFieldPrecioRecetas;
    private javax.swing.JTextField jTextFieldRol;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFielddni;
    // End of variables declaration//GEN-END:variables
}
