
package gui;

import aplicacion.Empleado;
import aplicacion.FachadaAplicacion;
import aplicacion.Zonas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;

/**
 *
 * @author alumnogreibd
 */
public class VModificarEmpleado extends javax.swing.JDialog {
    
    
    private FachadaAplicacion fa;
    private Empleado anterior;
    private ModeloListaZonas modeloTrabaja;
    private ModeloListaZonas modeloNoTrabaja;

    /**
     * Creates new form VAnhadirEmpleados
     * @param parent
     * @param modal
     * @param fa
     * @param anterior
     */
    public VModificarEmpleado(java.awt.Frame parent, boolean modal,FachadaAplicacion fa, Empleado anterior) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        centrarVentana(); 
        this.anterior=anterior;
        this.modeloTrabaja=new ModeloListaZonas();
        this.modeloNoTrabaja=new ModeloListaZonas();
        jListTrabajaEn.setModel(modeloTrabaja);
        jListNoTrabajaEn.setModel(modeloNoTrabaja);
        List<Zonas> trabaja=fa.zonasTrabaja(anterior);
        modeloTrabaja.setElementos(trabaja);
        List<Zonas> noTrabaja=fa.zonasNoTrabaja(anterior);
        modeloNoTrabaja.setElementos(noTrabaja);
        if (modeloTrabaja.getSize()==0) jButtonFlechaD.setEnabled(false);
        else jButtonFlechaD.setEnabled(true);
        if (modeloNoTrabaja.getSize()==0) jButtonFlechaI.setEnabled(false);
        else jButtonFlechaI.setEnabled(true);
        jTextFieldDNI.setText(anterior.getDni());
        jTextFieldNombre.setText(anterior.getNombre());
        jTextFieldRol.setText(anterior.getRol());
        jTextFieldContrasenha.setText(anterior.getContrasenha());
    }
    
    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDNI = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelRol = new javax.swing.JLabel();
        jLabelContrasenha = new javax.swing.JLabel();
        jLabelNoTrabajaEn = new javax.swing.JLabel();
        jLabelTrabajaEn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNoTrabajaEn = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTrabajaEn = new javax.swing.JList<>();
        jTextFieldContrasenha = new javax.swing.JTextField();
        jTextFieldRol = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jButtonFlechaD = new javax.swing.JButton();
        jButtonFlechaI = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Empleados");

        jLabelDNI.setText("DNI:");

        jLabelNombre.setText("Nombre:");

        jLabelRol.setText("Rol:");

        jLabelContrasenha.setText("Contraseña:");

        jLabelNoTrabajaEn.setText("No trabaja en:");

        jLabelTrabajaEn.setText("Trabaja en:");

        jListNoTrabajaEn.setModel(new ModeloListaZonas());
        jScrollPane1.setViewportView(jListNoTrabajaEn);

        jListTrabajaEn.setModel(new ModeloListaZonas());
        jScrollPane2.setViewportView(jListTrabajaEn);

        jTextFieldDNI.setEditable(false);

        jButtonFlechaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaD.png"))); // NOI18N
        jButtonFlechaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlechaDActionPerformed(evt);
            }
        });

        jButtonFlechaI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaI.png"))); // NOI18N
        jButtonFlechaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlechaIActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContrasenha)
                            .addComponent(jLabelRol)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelDNI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldRol)
                            .addComponent(jTextFieldContrasenha))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonFlechaD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonFlechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelTrabajaEn)
                                .addGap(85, 85, 85))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelNoTrabajaEn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDNI)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRol)
                            .addComponent(jTextFieldRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelContrasenha)
                            .addComponent(jTextFieldContrasenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAceptar)
                            .addComponent(jButtonCancelar))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTrabajaEn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNoTrabajaEn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButtonFlechaD)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonFlechaI)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFlechaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlechaDActionPerformed
        // TODO add your handling code here:
        modeloNoTrabaja.nuevoElemento(modeloNoTrabaja.obtenerZona(jListNoTrabajaEn.getSelectedIndex()));
        modeloTrabaja.borrarElemento(jListTrabajaEn.getSelectedIndex());
        if (modeloTrabaja.getSize()==0) jButtonFlechaD.setEnabled(false);
        else jListTrabajaEn.setSelectedIndex(0);
        jListNoTrabajaEn.setSelectedIndex(modeloTrabaja.getSize()-1);
        jButtonFlechaI.setEnabled(true);
    }//GEN-LAST:event_jButtonFlechaDActionPerformed

    private void jButtonFlechaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlechaIActionPerformed
        // TODO add your handling code here:
        modeloTrabaja.nuevoElemento(modeloTrabaja.obtenerZona(jListTrabajaEn.getSelectedIndex()));
        modeloNoTrabaja.borrarElemento(jListNoTrabajaEn.getSelectedIndex());
        if (modeloNoTrabaja.getSize()==0) jButtonFlechaI.setEnabled(false);
        else jListNoTrabajaEn.setSelectedIndex(0);
        jListTrabajaEn.setSelectedIndex(modeloNoTrabaja.getSize()-1);
        jButtonFlechaD.setEnabled(true);
    }//GEN-LAST:event_jButtonFlechaIActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        Empleado nuevo=new Empleado(anterior.getDni(),jTextFieldNombre.getText(),jTextFieldRol.getText(),jTextFieldContrasenha.getText());
        fa.modificarEmpleado(nuevo,modeloTrabaja.getElementos());
        this.dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonFlechaD;
    private javax.swing.JButton jButtonFlechaI;
    private javax.swing.JLabel jLabelContrasenha;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelNoTrabajaEn;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTrabajaEn;
    private javax.swing.JList<String> jListNoTrabajaEn;
    private javax.swing.JList<String> jListTrabajaEn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldContrasenha;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldRol;
    // End of variables declaration//GEN-END:variables
}
