
package gui;

import aplicacion.Receta;
import aplicacion.Bar;
import aplicacion.Producto;
import aplicacion.FachadaAplicacion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;

/**
 *
 * @author alumnogreibd
 */
public class VModificarReceta extends javax.swing.JDialog {

  
    
    private FachadaAplicacion fa;
    private Receta anterior;
    private ModeloListaBares modeloDisponible;
    private ModeloListaBares modeloNoDisponible;
    private ModeloTablaProductosReceta modeloProductos;
    
      /**
     * Creates new form VAnhadirEmpleados
     */
    public VModificarReceta(java.awt.Frame parent, boolean modal,FachadaAplicacion fa, Receta anterior) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        centrarVentana(); 
        this.fa=fa;
        this.anterior=anterior;
        this.modeloDisponible=new ModeloListaBares();
        this.modeloNoDisponible=new ModeloListaBares();
        this.modeloProductos=new ModeloTablaProductosReceta();
        jListDisponibleEn.setModel(modeloDisponible);
        jListNoDisponibleEn.setModel(modeloNoDisponible);
        jTableProductos.setModel(modeloProductos);
        jTextFieldNombre.setText(anterior.getNombre());
        jTextFieldPrecio.setText(Float.toString(anterior.getPrecio_venta()));
        List<Bar> baresDisponible=fa.baresRecetaDisponible(anterior);
        modeloDisponible.setElementos(baresDisponible);
        List<Bar> baresNoDisponible=fa.baresRecetaNoDisponible(anterior);
        modeloNoDisponible.setElementos(baresNoDisponible);
        if (modeloDisponible.getSize()==0) jButtonFlechaD.setEnabled(false);
        else jButtonFlechaD.setEnabled(true);
        if (modeloNoDisponible.getSize()==0) jButtonFlechaI.setEnabled(false);
        else jButtonFlechaI.setEnabled(true);
        List<Producto> productos=fa.todosLosProductos();
        List<Float> cantidades=fa.emparejarCantidadesProductos(anterior,productos);
        modeloProductos.setFilas(productos,cantidades);
    }
    
    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelProductos = new javax.swing.JLabel();
        jLabelNoDisponibleEn = new javax.swing.JLabel();
        jLabelDisponibleEn = new javax.swing.JLabel();
        jScrollPaneNoDisponibleEn = new javax.swing.JScrollPane();
        jListNoDisponibleEn = new javax.swing.JList<>();
        jScrollPaneDisponibleEn = new javax.swing.JScrollPane();
        jListDisponibleEn = new javax.swing.JList<>();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonFlechaD = new javax.swing.JButton();
        jButtonFlechaI = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Recetas");

        jLabelNombre.setText("Nombre:");

        jLabelPrecio.setText("Precio:");

        jLabelProductos.setText("Productos:");

        jLabelNoDisponibleEn.setText("No disponible en:");

        jLabelDisponibleEn.setText("Disponible en:");

        jListNoDisponibleEn.setModel(new ModeloListaBares());
        jScrollPaneNoDisponibleEn.setViewportView(jListNoDisponibleEn);

        jListDisponibleEn.setModel(new ModeloListaBares());
        jScrollPaneDisponibleEn.setViewportView(jListDisponibleEn);

        jTextFieldNombre.setEditable(false);

        jButtonFlechaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaD.png"))); // NOI18N
        jButtonFlechaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlechaDActionPerformed(evt);
            }
        });

        jButtonFlechaI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaI.png"))); // NOI18N
        jButtonFlechaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlechaIActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableProductos.setModel(new ModeloTablaProductosReceta());
        jScrollPaneProductos.setViewportView(jTableProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelProductos)
                                .addComponent(jLabelPrecio)
                                .addComponent(jLabelNombre))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(jTextFieldPrecio)))
                        .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jButtonAceptar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPaneDisponibleEn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonFlechaD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonFlechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelDisponibleEn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNoDisponibleEn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPaneNoDisponibleEn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jButtonCancelar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAceptar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoDisponibleEn)
                    .addComponent(jLabelDisponibleEn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneDisponibleEn, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jScrollPaneNoDisponibleEn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButtonFlechaD)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFlechaI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButtonCancelar)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonFlechaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlechaDActionPerformed
        // TODO add your handling code here:
        modeloNoDisponible.nuevoElemento(modeloDisponible.obtenerBar(jListNoDisponibleEn.getSelectedIndex()));
        modeloDisponible.borrarElemento(jListDisponibleEn.getSelectedIndex());
        if (modeloDisponible.getSize()==0) jButtonFlechaD.setEnabled(false);
        else jListDisponibleEn.setSelectedIndex(0);
        jListNoDisponibleEn.setSelectedIndex(modeloDisponible.getSize()-1);
        jButtonFlechaI.setEnabled(true);
    }//GEN-LAST:event_jButtonFlechaDActionPerformed

    private void jButtonFlechaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlechaIActionPerformed
        // TODO add your handling code here:
        modeloDisponible.nuevoElemento(modeloNoDisponible.obtenerBar(jListNoDisponibleEn.getSelectedIndex()));
        modeloNoDisponible.borrarElemento(jListNoDisponibleEn.getSelectedIndex());
        if (modeloNoDisponible.getSize()==0) jButtonFlechaI.setEnabled(false);
        else jListNoDisponibleEn.setSelectedIndex(0);
        jListDisponibleEn.setSelectedIndex(modeloNoDisponible.getSize()-1);
        jButtonFlechaD.setEnabled(true);
    }//GEN-LAST:event_jButtonFlechaIActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        Receta nueva=new Receta(anterior.getNombre(),Float.valueOf(jTextFieldPrecio.getText()).floatValue());
        fa.modificarReceta(nueva,modeloDisponible.getElementos(),modeloProductos.getProductos(),modeloProductos.getCantidades());
        this.dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonFlechaD;
    private javax.swing.JButton jButtonFlechaI;
    private javax.swing.JLabel jLabelDisponibleEn;
    private javax.swing.JLabel jLabelNoDisponibleEn;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JList<String> jListDisponibleEn;
    private javax.swing.JList<String> jListNoDisponibleEn;
    private javax.swing.JScrollPane jScrollPaneDisponibleEn;
    private javax.swing.JScrollPane jScrollPaneNoDisponibleEn;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
