/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.Zonas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author david
 */
public class VPrincipalE extends javax.swing.JFrame {

    aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VPrincipalE
     */
    public VPrincipalE() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        centrarVentana();        
    }
    
    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEmpleados = new javax.swing.JPanel();
        zonasButton = new javax.swing.JButton();
        juegosButton = new javax.swing.JButton();
        desplegableButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setIconImages(null);
        getContentPane().setLayout(null);

        panelEmpleados.setBackground(new java.awt.Color(255, 255, 255));

        zonasButton.setText("Zonas");
        zonasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonasButtonActionPerformed(evt);
            }
        });

        juegosButton.setText("Juegos");
        juegosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(juegosButton)
                .addGap(18, 18, 18)
                .addComponent(zonasButton)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juegosButton)
                    .addComponent(zonasButton))
                .addContainerGap())
        );

        getContentPane().add(panelEmpleados);
        panelEmpleados.setBounds(52, 6, 613, 40);

        desplegableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/barras.jpg"))); // NOI18N
        desplegableButton.setMaximumSize(new java.awt.Dimension(40, 40));
        desplegableButton.setMinimumSize(new java.awt.Dimension(40, 40));
        desplegableButton.setPreferredSize(new java.awt.Dimension(40, 40));
        desplegableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableButtonActionPerformed(evt);
            }
        });
        getContentPane().add(desplegableButton);
        desplegableButton.setBounds(6, 6, 40, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 52, 660, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zonasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonasButtonActionPerformed
        // TODO add your handling code here:
        java.util.List<Zonas> zonas = fa.consultarZonas(null);
        VZonas vc;
        vc = new VZonas(this, true, fa, zonas);
        vc.setVisible(true);
    }//GEN-LAST:event_zonasButtonActionPerformed

    private void juegosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegosButtonActionPerformed

        
        
    }//GEN-LAST:event_juegosButtonActionPerformed

    private void desplegableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegableButtonActionPerformed
        // TODO add your handling code here:
        if (panelEmpleados.isVisible()) {
            // Si está visible, lo hacemos invisible
            panelEmpleados.setVisible(false);
        } else {
            // Si no está visible, lo hacemos visible
            panelEmpleados.setVisible(true);
        }
    }//GEN-LAST:event_desplegableButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton desplegableButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton juegosButton;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JButton zonasButton;
    // End of variables declaration//GEN-END:variables
}
