/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.FichasDeUsuario;
import aplicacion.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author alumnogreibd
 */
public class VPrincipalU extends javax.swing.JFrame {
    
    aplicacion.FachadaAplicacion fa;
    Usuario usuario;

    /**
     * Creates new form VPrincipalU
     */
    public VPrincipalU(aplicacion.FachadaAplicacion fa, Usuario usuario) {
        this.fa=fa;
        this.usuario=usuario;
        initComponents();
        centrarVentana();
        getContentPane().setBackground(Color.WHITE);
        btnGuardar.setEnabled(false);
        nombrePerfil.setEditable(false);
        nombrePerfil.setText(usuario.getNickname());
        contrasenhaPerfil.setEditable(false);
        contrasenhaPerfil.setText(usuario.getContrasenha());
        saldoPerfil.setEditable(false);
        saldoPerfil.setText(String.valueOf(usuario.getSaldo()));
        actualizarFichas();
    }

    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        this.setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelPerfil = new javax.swing.JPanel();
        nombrePerfil = new javax.swing.JTextField();
        contrasenhaPerfil = new javax.swing.JTextField();
        saldoPerfil = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelContrasenha = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        scrollFichas = new javax.swing.JScrollPane();
        listaFichas = new javax.swing.JList<>();
        Fichas = new javax.swing.JLabel();
        cantidadFichas = new javax.swing.JTextField();
        labelCantidad = new javax.swing.JLabel();
        panelJuegos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPerfil.setToolTipText("");

        labelNombre.setText("Nombre:");

        labelContrasenha.setText("Contraseña:");

        labelSaldo.setText("Saldo:");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        listaFichas.setModel(new ModeloListaStrings());
        listaFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFichasMouseClicked(evt);
            }
        });
        scrollFichas.setViewportView(listaFichas);

        Fichas.setText("Fichas");

        labelCantidad.setText("Cantidad:");

        javax.swing.GroupLayout panelPerfilLayout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(panelPerfilLayout);
        panelPerfilLayout.setHorizontalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelContrasenha)
                            .addComponent(labelSaldo))
                        .addGap(18, 18, 18)
                        .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasenhaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPerfilLayout.createSequentialGroup()
                                .addComponent(saldoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar))))
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addGap(41, 41, 41)
                        .addComponent(nombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrollFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addComponent(labelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantidadFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fichas)
                .addGap(93, 93, 93))
        );
        panelPerfilLayout.setVerticalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fichas)
                .addGap(2, 2, 2)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre)
                            .addComponent(btnEditar))
                        .addGap(18, 18, 18)
                        .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contrasenhaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelContrasenha))
                        .addGap(18, 18, 18)
                        .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSaldo)
                            .addComponent(btnGuardar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCantidad))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Perfil", panelPerfil);
        panelPerfil.getAccessibleContext().setAccessibleName("panelPerfil");

        javax.swing.GroupLayout panelJuegosLayout = new javax.swing.GroupLayout(panelJuegos);
        panelJuegos.setLayout(panelJuegosLayout);
        panelJuegosLayout.setHorizontalGroup(
            panelJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        panelJuegosLayout.setVerticalGroup(
            panelJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Juegos", panelJuegos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        fa.editarUsuario(this.usuario.getDni(), nombrePerfil.getText(), this.usuario.getSaldo(), contrasenhaPerfil.getText());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        nombrePerfil.setEditable(true);
        contrasenhaPerfil.setEditable(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void listaFichasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFichasMouseClicked
        String color=listaFichas.getSelectedValue();
        FichasDeUsuario fdu=fa.buscarMasaDeFichas(this.usuario.getDni(), color);
        
        cantidadFichas.setText(String.valueOf(fdu.getCantidad()));
    }//GEN-LAST:event_listaFichasMouseClicked

    private void actualizarFichas(){
        ModeloListaStrings mlf=(ModeloListaStrings)listaFichas.getModel();
        ArrayList<FichasDeUsuario> resFichasDU=fa.buscarFichasDeUsuario(this.usuario.getDni());
        ArrayList<String> fichas=new ArrayList<>();
        
        for (FichasDeUsuario fdu:resFichasDU){
            fichas.add(fdu.getColor());
        }
        
        mlf.setElementos(fichas);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fichas;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField cantidadFichas;
    private javax.swing.JTextField contrasenhaPerfil;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelContrasenha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JList<String> listaFichas;
    private javax.swing.JTextField nombrePerfil;
    private javax.swing.JPanel panelJuegos;
    private javax.swing.JPanel panelPerfil;
    private javax.swing.JTextField saldoPerfil;
    private javax.swing.JScrollPane scrollFichas;
    // End of variables declaration//GEN-END:variables
}
