
package gui;

import aplicacion.FachadaAplicacion;
import aplicacion.Zonas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author david
 */
public class VPrincipalE extends javax.swing.JFrame {

    aplicacion.FachadaAplicacion fa;
    FachadaGui fgui;
    /**
     * Creates new form VPrincipalE
     * @param parent
     * @param modal
     * @param fa
     */
    public VPrincipalE(FachadaAplicacion fa, FachadaGui fgui) {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        this.fa=fa;
        this.fgui=fgui;
        centrarVentana(); 

        setEnabled(true);
        setFocusable(true);
        setFocusableWindowState(true);
    }
    
    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zonasButton = new javax.swing.JButton();
        gestionButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal Empleado");
        setEnabled(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zonasButton.setBackground(new java.awt.Color(255, 255, 255));
        zonasButton.setForeground(new java.awt.Color(255, 255, 255));
        zonasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/zonas.png"))); // NOI18N
        zonasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(zonasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 90, 250, 240));

        gestionButton.setBackground(new java.awt.Color(255, 255, 255));
        gestionButton.setForeground(new java.awt.Color(255, 255, 255));
        gestionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/gestion.png"))); // NOI18N
        gestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gestionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 250));

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zonasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonasButtonActionPerformed
        VZonas vc;
        vc = new VZonas(this, true, fa, fgui);
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_zonasButtonActionPerformed

    private void gestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionButtonActionPerformed
        VEmRePrDeSe vc;
        vc = new VEmRePrDeSe(this, true, fa, fgui);
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gestionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton zonasButton;
    // End of variables declaration//GEN-END:variables
}
